#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mp3-converter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp3-converter
  template:
    metadata:
      labels:
        app: mp3-converter
    spec:
      containers:
      - name: mp3-converter
        image: teateatea/mp3_converter
        ports:
        - containerPort: 5000
        - containerPort: 5001
---
#LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: mp3-converter-service
spec:
  selector:
    app: mp3-converter
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
---
#Autoscaler
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mp3-converter-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mp3-converter-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
