#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  {{ with .Values}}
  replicas: {{ .replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
      - name: {{ .Release.Name }}-web
        {{ with .Values.container }}
        image: {{ .image }}
        {{ end }}
        ports:
        - containerPort: 5000
        - containerPort: 5001

---
# LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-deployment
  ports:
    - name: http-port-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: http-port-5001
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer

---
#Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-deployment
  {{ with .Values.hpa }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  {{ end }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
